text = input()
print(text.count('oo'))
print(text.count('oo', 0, 8))
print()
print(text.startswith('bo'))
print(text.startswith('zor'))
print()
print(text.endswith('bo'))
print(text.endswith('zor'))
print()
print(text.find('bo'))
print(text.find('zor'))
print(text.find('choykhona'))
print()
print(text.rfind('bo'))
print(text.rfind('zor'))
print(text.rfind('choykhona'))
print()
# print(text.index('bo'))    not recomended to use. Better use find or rfind 
# print(text.rindex('bo'))   not recomended to use. Better use find or rfind
print()
print(text.strip())
print(text.Istrip())
print(text.rtrip())
print()
print(text.replace('bo', 'choykhona'))
print(text.replace('bo', 'choykhona', 2))    # 2 means amount of replacement