text = input()
print(text.isalnum())
print('som123'.isalnum())
print('som12*3'.isalnum())
print('s'.isalnum())
print()
print(text.isalpha())
print('somKLJFSD'.isalpha())
print('som12'.isalpha())
print(''.isalpha())
print()
print(text.isdigit())
print('2234'.isdigit())
print('som234'.isdigit())
print('som234*'.isdigit())
print(''.isdigit())
print()
print(text.islower())                  # digits and symbols are not considered
print('aksdjfh'.islower())
print('alksdf*&^%$#@'.islower())
print('alskd123'.islower())
print('AAAAas'.islower())
print()
print(text.isupper())                 # digits and symbols are not considered
print('ADF'.isupper())
print('AFJ123***'.isupper())
print('ASDFaaaaaa'.isupper())
print()
print(text.isspace())
print('     '.isspace())
print(' '.isspace())
print(''.isspace())
print('aksdfj'.isspace())
print('letter number1 symbol*'.isspace())